# Generated by Django 3.0.8 on 2020-07-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_question_question_text2'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ml',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '5')], default='', max_length=200),
            preserve_default=False,
        ),
    ]
