# Generated by Django 3.0.8 on 2020-07-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Izd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izd_cod', models.CharField(default='9999', max_length=4)),
                ('izd_name', models.CharField(default='Название', max_length=100)),
                ('izd_des', models.CharField(default='', max_length=100)),
            ],
            options={
                'ordering': ['izd_name'],
            },
        ),
        migrations.CreateModel(
            name='Harak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_cod', models.CharField(default='9999', max_length=4)),
                ('color_name', models.CharField(default='Название', max_length=100)),
                ('color_des', models.CharField(default='', max_length=100)),
                ('izds', models.ManyToManyField(to='Et.Izd')),
            ],
            options={
                'ordering': ['color_name'],
            },
        ),
    ]
