# Generated by Django 3.0.8 on 2020-07-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Et', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harak',
            name='izds',
        ),
        migrations.AddField(
            model_name='izd',
            name='haraks',
            field=models.ManyToManyField(to='Et.Harak'),
        ),
    ]
