# Generated by Django 3.0.8 on 2020-07-17 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Et', '0002_auto_20200717_2047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='harak',
            options={'ordering': ['color_name'], 'verbose_name': 'Характеристика', 'verbose_name_plural': 'Характеристика'},
        ),
        migrations.AlterModelOptions(
            name='izd',
            options={'ordering': ['izd_name'], 'verbose_name': 'Номенклатура', 'verbose_name_plural': 'Номенклатура'},
        ),
        migrations.RemoveField(
            model_name='izd',
            name='haraks',
        ),
        migrations.AlterField(
            model_name='harak',
            name='color_cod',
            field=models.CharField(default='9999', max_length=4, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='harak',
            name='color_des',
            field=models.CharField(default='', max_length=100, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='harak',
            name='color_name',
            field=models.CharField(default='Название', max_length=100, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='izd',
            name='izd_cod',
            field=models.CharField(default='9999', max_length=4, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='izd',
            name='izd_des',
            field=models.CharField(default='', max_length=100, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='izd',
            name='izd_name',
            field=models.CharField(default='Название', max_length=100, verbose_name='Номенклатура'),
        ),
        migrations.CreateModel(
            name='Upak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(default='1', max_length=4, verbose_name='Номер')),
                ('tip', models.CharField(default='ST', max_length=4, verbose_name='Тип')),
                ('haraks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Et.Harak')),
            ],
            options={
                'verbose_name': 'Упаковки',
                'verbose_name_plural': 'Упаковки',
                'ordering': ['num'],
            },
        ),
        migrations.AddField(
            model_name='izd',
            name='ups',
            field=models.ManyToManyField(to='Et.Upak', verbose_name='Упаковки'),
        ),
    ]
