# Generated by Django 3.0.8 on 2020-07-17 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Et', '0003_auto_20200717_2116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='harak',
            options={'ordering': ['color_name'], 'verbose_name': 'Свойства', 'verbose_name_plural': 'Свойства'},
        ),
        migrations.RemoveField(
            model_name='izd',
            name='ups',
        ),
        migrations.AlterField(
            model_name='harak',
            name='color_des',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='izd',
            name='izd_des',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='upak',
            name='haraks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Et.Harak', verbose_name='Свойства'),
        ),
    ]
