# Generated by Django 3.0.8 on 2020-07-17 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Et', '0004_auto_20200717_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='upak',
            name='izds',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Et.Izd', verbose_name='Номенклатура'),
            preserve_default=False,
        ),
    ]
