# Generated by Django 3.0.8 on 2020-07-17 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Et', '0005_upak_izds'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='harak',
            options={},
        ),
        migrations.AlterModelOptions(
            name='izd',
            options={},
        ),
        migrations.AlterModelOptions(
            name='upak',
            options={},
        ),
        migrations.RemoveField(
            model_name='harak',
            name='color_cod',
        ),
        migrations.RemoveField(
            model_name='harak',
            name='color_des',
        ),
        migrations.RemoveField(
            model_name='harak',
            name='color_name',
        ),
        migrations.RemoveField(
            model_name='izd',
            name='izd_cod',
        ),
        migrations.RemoveField(
            model_name='izd',
            name='izd_des',
        ),
        migrations.RemoveField(
            model_name='izd',
            name='izd_name',
        ),
        migrations.RemoveField(
            model_name='upak',
            name='haraks',
        ),
        migrations.RemoveField(
            model_name='upak',
            name='izds',
        ),
        migrations.RemoveField(
            model_name='upak',
            name='num',
        ),
        migrations.RemoveField(
            model_name='upak',
            name='tip',
        ),
    ]
