# Generated by Django 3.0.8 on 2020-07-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Et', '0006_auto_20200717_2213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='harak',
            options={'ordering': ['color_name'], 'verbose_name': 'Свойства', 'verbose_name_plural': 'Свойства'},
        ),
        migrations.AlterModelOptions(
            name='izd',
            options={'ordering': ['izd_name'], 'verbose_name': 'Номенклатура', 'verbose_name_plural': 'Номенклатура'},
        ),
        migrations.AddField(
            model_name='harak',
            name='color_cod',
            field=models.CharField(default='9999', max_length=4, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='harak',
            name='color_des',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='harak',
            name='color_name',
            field=models.CharField(default='Название', max_length=100, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='izd',
            name='izd_cod',
            field=models.CharField(default='9999', max_length=4, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='izd',
            name='izd_des',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='izd',
            name='izd_name',
            field=models.CharField(default='Название', max_length=100, verbose_name='Номенклатура'),
        ),
    ]
